### ISSUE TITLE
なんだろう、 RocksDB でコケるのやめてもらっていいですか？

### ISSUE THREAD

**Issue by makotia** [TechharaInc/kwbot#1]
素直に今後のことも考えて普通の DB 使った方がいい。
![image](https://user-images.githubusercontent.com/22451396/116099281-c56ee480-a6e6-11eb-9456-37d775b52ed6.png)

**Comment by TinyKitten** [comment]
エラーはエラーであると見抜ける人でないと(Rustを使うのは)難しい

**Comment by makotia** [comment]
それって Alpine Linux の問題ですよね？
