### ISSUE TITLE
エイリアス

### ISSUE THREAD

**Issue by TinyKitten** [TechharaInc/kwbot#7]
## ..alias hiroyuki noda
なんだろう、 ..hiroyuki でよくないですか？

**Comment by makotia** [comment]
これはエイ
![image](https://user-images.githubusercontent.com/22451396/116805616-a0ed8f00-ab62-11eb-828e-daaefb3a2d11.png)

**Comment by TinyKitten** [comment]
![image](https://user-images.githubusercontent.com/32848922/116805735-5f111880-ab63-11eb-989a-25e83853d914.png)
これはリアス線
